
[source=ISO34000]
== Terms and definitions

=== code

data representation in different forms according to a pre-established set of
rules

[.source]
<<ISO639-2>>

=== calendar code

{{code}} used to represent a calendar system


=== language code

combination of characters used to represent the name of a language or languages

[.source]
<<ISO5127,clause="3.2.5.14">>


=== script code

combination of characters used to represent the name of a script

[.source]
<<ISO15924,clause="3.8">>


=== registration item

data element in a register

=== registration code

code that identifies a {{registration item}} within a register

=== ISO 34300 registration authority
alt:[ISO 34300/RA]

registration authority that manages the {{ISO 34300 register}}

=== ISO 34300 register

register containing {{ISO 34300 registration item,ISO 34300 registration items}}

=== ISO 34300 advisory group
alt:[ISO 34300/AG]

group that provides advice to the {{ISO 34300 registration authority}} on the
contents of the {{ISO 34300 register}}

=== ISO 34300 registration item

registration item identified by a registration code unique to the
{{ISO 34300 register}}

